# Generated by Django 5.0.6 on 2024-06-08 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(max_length=15000)),
                ("key", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=1000)),
                ("option1", models.TextField(max_length=1000)),
                ("option2", models.TextField(max_length=1000)),
                ("option3", models.TextField(max_length=1000)),
                ("option4", models.TextField(max_length=1000)),
                (
                    "answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.bundle"
                    ),
                ),
            ],
        ),
    ]
