# Generated by Django 5.0.6 on 2024-06-08 21:05

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundle",
            name="key",
        ),
        migrations.AlterField(
            model_name="bundle",
            name="id",
            field=models.CharField(
                default=project.models.generate_unique_id,
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
