# Generated by Django 5.0.6 on 2024-06-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_bundle_key_alter_bundle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
