# Generated by Django 4.1.7 on 2024-06-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_bundle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
